# name: Scrape Cinema Regions

# on:
#   schedule:
#     - cron: "*/2 * * * *"   # Runs every day at 12 AM UTC
#   workflow_dispatch:  # Allows manual triggering

# jobs:
#   scrape_cinema_data:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Set Up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Install Dependencies
#         run: pip install requests beautifulsoup4 pandas

#       - name: Run Scraper
#         run: python code/crawler.py  # Ensure the script is named `scraper.py`

#       - name: Commit and Push CSV
#         run: |
#           git config --global user.name "GitHub Actions"
#           git config --global user.email "actions@github.com"
#           git add data/cinema_regions.csv
#           git commit -m "Update cinema regions data"
#           git push
